version: "3.8"

services:
  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx-gateway/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
